version: '3'

services:

  adminsystem-db:
    image: postgres:16
    container_name: adminsystem-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      TZ: 'Etc/GMT+3'
      PGTZ: 'Etc/GMT+3'
    volumes:
      - adminsystem-db-vol:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
volumes:
  adminsystem-db-vol:
    driver: local